name: publish
on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-rc.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup jdk 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}
          restore-keys: |
            - ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: |
            - ${{ runner.os }}-gradlewrapper-
      - name: Publish candidate
        if: contains(github.ref, '-rc.')
        run: ./gradlew --info --stacktrace -Prelease.useLastTag=true candidate
        env:
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.signingKey }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.signingPassword }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.netflixOssUsername }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.netflixOssPassword }}
      - name: Publish release
        if: (!contains(github.ref, '-rc.'))
        run: ./gradlew --info --stacktrace -Dgradle.publish.key=${{ secrets.gradlePublishKey }} -Dgradle.publish.secret=${{ secrets.gradlePublishSecret }} -Prelease.useLastTag=true final
        env:
          NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.sonatypeUsername }}
          NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.sonatypePassword }}
          NETFLIX_OSS_SIGNING_KEY: ${{ secrets.signingKey }}
          NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.signingPassword }}
          NETFLIX_OSS_REPO_USERNAME: ${{ secrets.netflixOssUsername }}
          NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.netflixOssPassword }}